Importante, instalar pyarrow y pandas para poder ver el dataset

**Esta parte solo sirvio para poder borrar algunos datos que no otorgaban informacion valiosa, el data set nuevo se llama dataset.parquet, el original se puede encontrar en la pagina web HugginFace: https://huggingface.co/datasets/somosnlp/spanish_medica_llm**

In [2]:
import pandas as pd

In [3]:
df = pd.read_parquet('./raw_dataset.parquet')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2136490 entries, 0 to 2136489
Data columns (total 8 columns):
 #   Column         Dtype
---  ------         -----
 0   raw_text       object
 1   topic          object
 2   speciallity    object
 3   raw_text_type  object
 4   topic_type     object
 5   source         object
 6   country        object
 7   document_id    object
dtypes: object(8)
memory usage: 130.4+ MB

In [5]:
df_filtrado = df

In [19]:
# Visualizacion segun fuente
df_filtrado[(df_filtrado["source"] == '1')]

,raw_text,topic,speciallity,raw_text_type,topic_type,source,country,document_id
0,Anamnesis\nSe trata de un paciente de 67 años ...,"Adenocarcinoma, SAI",,clinic_case,medical_diagnostic,1,es,1
1,Anamnesis\nSe trata de un paciente de 67 años ...,"Adenocarcinoma, SAI - grado I, bien diferenciado",,clinic_case,medical_diagnostic,1,es,1
2,Anamnesis\nSe trata de un paciente de 67 años ...,Neoplasia metastásica,,clinic_case,medical_diagnostic,1,es,1
3,Anamnesis\nSe trata de un paciente de 67 años ...,Neoplasia de benignidad o malignidad incierta,,clinic_case,medical_diagnostic,1,es,1
4,Anamnesis\nSe trata de un paciente de 67 años ...,"Adenocarcinoma metastásico, SAI",,clinic_case,medical_diagnostic,1,es,1
...,...,...,...,...,...,...,...,...
1594,Anamnesis\nSe trata de una mujer de 61 años de...,Neoplasia de benignidad o malignidad incierta,,clinic_case,medical_diagnostic,1,es,597
1595,Anamnesis\nSe trata de una mujer de 61 años de...,"Carcinoma ductal infiltrante, SAI - grado II, ...",,clinic_case,medical_diagnostic,1,es,597
1596,"Anamnesis\nPaciente mujer de 72 años, natural ...","Carcinoma ductal infiltrante, SAI",,clinic_case,medical_diagnostic,1,es,599
1597,"Anamnesis\nPaciente mujer de 72 años, natural ...",Neoplasia metastásica,,clinic_case,medical_diagnostic,1,es,599
1598,"Anamnesis\nPaciente mujer de 72 años, natural ...",Neoplasia de benignidad o malignidad incierta,,clinic_case,medical_diagnostic,1,es,599

In [7]:
# Eliminacion de los datos feos
df_filtrado = df_filtrado.drop(df_filtrado[df_filtrado['source'] == '2'].index)
df_filtrado = df_filtrado.drop(df_filtrado[df_filtrado['source'] == '3'].index)
df_filtrado = df_filtrado.drop(df_filtrado[df_filtrado['source'] == '4'].index)
df_filtrado = df_filtrado.drop(df_filtrado[df_filtrado['source'] == '7'].index)
df_filtrado = df_filtrado.drop(df_filtrado[df_filtrado['source'] == '8'].index)
df_filtrado = df_filtrado.drop(df_filtrado[df_filtrado['source'] == '13'].index)

In [8]:
# Visualizacion segun documento y fuente
df_filtrado[(df_filtrado["document_id"] == '1') & (df_filtrado["source"] == '2')]

Empty DataFrame
Columns: [raw_text, topic, speciallity, raw_text_type, topic_type, source, country, document_id]
Index: []

In [9]:
df_filtrado.describe()

,raw_text,topic,speciallity,raw_text_type,topic_type,source,country,document_id
count,17015,17015,17015,17015,17015,17015,17015,17015
unique,14895,444,1,1,2,7,1,5028
top,Anamnesis\nVarón de 70 años con antecedentes p...,,,clinic_case,,10,es,
freq,16,14471,17015,17015,14379,9000,17015,9000

In [22]:
df_filtrado.to_parquet("dataset.parquet")

In [23]:
df2 = pd.read_parquet('./dataset.parquet')
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17015 entries, 0 to 2020867
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   raw_text       17015 non-null  object
 1   topic          17015 non-null  object
 2   speciallity    17015 non-null  object
 3   raw_text_type  17015 non-null  object
 4   topic_type     17015 non-null  object
 5   source         17015 non-null  object
 6   country        17015 non-null  object
 7   document_id    17015 non-null  object
dtypes: object(8)
memory usage: 1.2+ MB